// src/config/achievements.js

export const ACHIEVEMENTS = {
  first_blood: {
    id: 'first_blood',
    name: 'First Blood',
    description: 'Kill your first dino',
    icon: '🦖',
    check: (stats) => stats.totalKills >= 1,
  },
  dino_slayer: {
    id: 'dino_slayer',
    name: 'Dino Slayer',
    description: 'Kill 100 dinos total',
    icon: '⚔️',
    check: (stats) => stats.totalKills >= 100,
  },
  extinction_event: {
    id: 'extinction_event',
    name: 'Extinction Event',
    description: 'Kill 1000 dinos total',
    icon: '☄️',
    check: (stats) => stats.totalKills >= 1000,
  },
  wave_5: {
    id: 'wave_5',
    name: 'Getting Started',
    description: 'Reach wave 5',
    icon: '🌊',
    check: (stats) => stats.highWave >= 5,
  },
  wave_10: {
    id: 'wave_10',
    name: 'Survivor',
    description: 'Reach wave 10',
    icon: '🏆',
    check: (stats) => stats.highWave >= 10,
  },
  combo_5: {
    id: 'combo_5',
    name: 'Combo Master',
    description: 'Get a 5x combo',
    icon: '🔥',
    check: (stats) => stats.maxCombo >= 5,
  },
  combo_10: {
    id: 'combo_10',
    name: 'Combo King',
    description: 'Get a 10x combo',
    icon: '👑',
    check: (stats) => stats.maxCombo >= 10,
  },
  chain_3: {
    id: 'chain_3',
    name: 'Chain Reaction',
    description: 'Kill 3 dinos with one bomber',
    icon: '💥',
    check: (stats) => stats.maxChain >= 3,
  },
  no_damage: {
    id: 'no_damage',
    name: 'Untouchable',
    description: 'Complete a wave without losing hearts',
    icon: '🛡️',
    check: (stats) => stats.perfectWaves >= 1,
  },
  score_1000: {
    id: 'score_1000',
    name: 'Rookie',
    description: 'Score 1,000 points',
    icon: '⭐',
    check: (stats) => stats.highScore >= 1000,
  },
  score_5000: {
    id: 'score_5000',
    name: 'Pro',
    description: 'Score 5,000 points',
    icon: '🌟',
    check: (stats) => stats.highScore >= 5000,
  },
  score_10000: {
    id: 'score_10000',
    name: 'Legend',
    description: 'Score 10,000 points',
    icon: '💫',
    check: (stats) => stats.highScore >= 10000,
  },
  mutation_max: {
    id: 'mutation_max',
    name: 'Fully Mutated',
    description: 'Max out all mutations in one run',
    icon: '🧬',
    check: (stats) => stats.maxMutations >= 6,
  },
  konami: {
    id: 'konami',
    name: 'Secret Hunter',
    description: 'Find a secret code',
    icon: '🔓',
    check: (stats) => stats.secretsFound >= 1,
  },
  games_10: {
    id: 'games_10',
    name: 'Dedicated',
    description: 'Play 10 games',
    icon: '🎮',
    check: (stats) => stats.totalGames >= 10,
  },
};

export const EGG_SKINS = {
  default: {
    id: 'default',
    name: 'Meteor Egg',
    color: 0xffcc00,
    glowColor: 0xff8800,
    unlocked: true,
  },
  ice: {
    id: 'ice',
    name: 'Ice Comet',
    color: 0x88ffff,
    glowColor: 0x00ffff,
    requirement: 'score_5000',
  },
  fire: {
    id: 'fire',
    name: 'Fireball',
    color: 0xff4400,
    glowColor: 0xff0000,
    requirement: 'dino_slayer',
  },
  rainbow: {
    id: 'rainbow',
    name: 'Rainbow',
    color: 0xffffff,
    glowColor: 0xff00ff,
    requirement: 'wave_10',
    special: 'rainbow', // Cycles colors
  },
  gold: {
    id: 'gold',
    name: 'Golden Egg',
    color: 0xffd700,
    glowColor: 0xffaa00,
    requirement: 'score_10000',
  },
  void: {
    id: 'void',
    name: 'Void Orb',
    color: 0x440088,
    glowColor: 0x8800ff,
    requirement: 'extinction_event',
  },
};
